## = Application Configuration
spring.application.name=auth-srv
spring.profiles.active=dev
server.port=8182
spring.jackson.property-naming-strategy=SNAKE_CASE

## = Config Server
spring.config.import=optional:configserver:${VAULT_URL:http://localhost:8185}
spring.cloud.config.token=${VAULT_TOKEN}

## = JWT Configuration
jwt.clock-skew-seconds=${application.jwt.clock-skew-seconds}

## = Database Configuration
spring.datasource.url=${application.database.base-url}/j2n_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${application.database.username}
spring.datasource.password=${application.database.password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

## = JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

## = Cloud Configuration
spring.cloud.compatibility-verifier.enabled=false

## = Logging Configuration
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

## = Swagger Configuration
spring.api-docs.enabled=true
spring.swagger-ui.enabled=true

## = RabbitMQ Configuration
spring.rabbitmq.host=${application.rabbitmq.host}
spring.rabbitmq.port=${application.rabbitmq.port}
spring.rabbitmq.username=${application.rabbitmq.username}
spring.rabbitmq.password=${application.rabbitmq.password}
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3

## = Redis Configuration
spring.data.redis.host=${application.redis.host}
spring.data.redis.port=${application.redis.port}
spring.data.redis.password=${application.redis.password}
spring.data.redis.database=0
spring.data.redis.timeout=${application.redis.timeout}