CREATE TABLE IF NOT EXISTS room_objects (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    room_id BIGINT,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'GOOD', -- GOOD, BROKEN, NEED_REPLACE
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (room_id) REFERENCES rooms(id)
);
