CREATE TABLE IF NOT EXISTS room_fees (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    room_id BIGINT,
    fee_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (room_id) REFERENCES rooms(id),
    FOREIGN KEY (fee_id) REFERENCES fees(id)
);
