# = Server Configuration
server.port=8180
spring.application.name=bff-srv
spring.profiles.active=dev

spring.config.import=optional:configserver:${VAULT_URL:http://localhost:8185}
spring.cloud.config.token=${VAULT_TOKEN}

api-gateway.base-url=${application.api-gateway.base-url}

spring.cloud.compatibility-verifier.enabled=false

spring.api-docs.enabled=true
spring.swagger-ui.enabled=true
spring.servlet.multipart.max-file-size=${application.multipart.max-file-size}
spring.servlet.multipart.max-request-size=${application.multipart.max-request-size}