spring.application.name=image-srv
spring.profiles.active=dev
server.port=8183
spring.jackson.property-naming-strategy=SNAKE_CASE

spring.config.import=optional:configserver:${VAULT_URL:http://localhost:8185}
spring.cloud.config.token=${VAULT_TOKEN}

spring.cloud.compatibility-verifier.enabled=false

# MySQL Database Configuration
spring.datasource.url=${application.database.base-url}/j2n_image?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${application.database.username}
spring.datasource.password=${application.database.password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.api-docs.enabled=true
spring.swagger-ui.enabled=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=${application.multipart.max-file-size}
spring.servlet.multipart.max-request-size=${application.multipart.max-request-size}

# Minio Configuration
minio.url=${image.minio.url}
minio.access-key=${image.minio.access-key}
minio.secret-key=${image.minio.secret-key}

## = RabbitMQ Configuration
spring.rabbitmq.host=${application.rabbitmq.host}
spring.rabbitmq.port=${application.rabbitmq.port}
spring.rabbitmq.username=${application.rabbitmq.username}
spring.rabbitmq.password=${application.rabbitmq.password}
spring.rabbitmq.virtual-host=/
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true