services:
  flowable-ui:
    build: .
    image: flowable-ui:6.8.0-patched
    # image: flowable/flowable-ui:6.8.0
    container_name: flowable-ui
    # restart: unless-stopped
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/keycloak?currentSchema=flowable
      SPRING_DATASOURCE_USERNAME: keycloak
      SPRING_DATASOURCE_PASSWORD: keycloak
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: flowable-ui
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: "fR7JY7uJgHjwTLFlh9OPJ2KAGJRWf8fX"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_NAME: "Flowable UI"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_AUTHORIZATION_GRANT_TYPE: authorization_code
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT_URI: "{baseUrl}/login/oauth2/code/{registrationId}"
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_NAME_ATTRIBUTE: preferred_username

      # Cấu hình tường minh từng Endpoint để Spring không tự đi 'Discovery' và so sánh Issuer nữa
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI: http://localhost:8081/auth/realms/Flowable/protocol/openid-connect/auth
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: http://keycloak:8080/auth/realms/Flowable/protocol/openid-connect/token
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK_SET_URI: http://keycloak:8080/auth/realms/Flowable/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_URI: http://keycloak:8080/auth/realms/Flowable/protocol/openid-connect/userinfo
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE: openid,profile,email,flowable-scope


      FLOWABLE_COMMON_APP_SECURITY_TYPE: oauth2
      FLOWABLE_COMMON_APP_SECURITY_OAUTH2_AUTHORITIES-ATTRIBUTE: roles
      FLOWABLE_COMMON_APP_SECURITY_OAUTH2_GROUPS-ATTRIBUTE: userGroups
      FLOWABLE_COMMON_APP_SECURITY_OAUTH2_GROUPS_ATTRIBUTE: userGroups

      FLOWABLE_SECURITY_OAUTH2_CLIENT_MAPPER_LOAD-AUTHORITIES-FROM-IDENTITY-SERVICE: false
      FLOWABLE_COMMON_APP_ROLE_MAPPINGS_ACCESS_ADMIN: "access-admin,Admin"
      FLOWABLE_COMMON_APP_ROLE_MAPPINGS_ACCESS_MODELER: "access-modeler,Admin"
      FLOWABLE_COMMON_APP_ROLE_MAPPINGS_ACCESS_IDM: "access-idm,Admin"
      FLOWABLE_COMMON_APP_ROLE_MAPPINGS_ACCESS_TASK: "access-task,Admin,Taskers"
      FLOWABLE_COMMON_APP_ROLE_MAPPINGS_ACCESS_REST_API: "access-rest-api,Admin"

      FLOWABLE_DATABASE_SCHEMA: flowable
      FLOWABLE_DATABASE_SCHEMA_UPDATE: true
      FLOWABLE_COMMON_APP_DATABASE_SCHEMA_UPDATE: true

      FLOWABLE_COMMON_APP_IDM_SERVICE_ENABLED: "true"
      FLOWABLE_IDM_SECURITY_TYPE: oauth2
      FLOWABLE_COMMON_APP_SECURITY_OAUTH2_USER-NAME-ATTRIBUTE: preferred_username
      FLOWABLE_IDM_READONLY: true
      FLOWABLE_SECURITY_OAUTH2_CLIENT_MAPPER_LOAD_AUTHORITIES_FROM_IDENTITY_SERVICE: false

      FLOWABLE_IDM_LDAP_SERVER: "ldap://openldap"
      FLOWABLE_IDM_LDAP_PORT: 389 
      FLOWABLE_IDM_LDAP_ENABLED: true
      FLOWABLE_IDM_LDAP_BASE_DN: "dc=flowable,dc=com"
      FLOWABLE_IDM_LDAP_USER_BASE_DN: "ou=users,dc=flowable,dc=com"
      FLOWABLE_IDM_LDAP_USER: "cn=admin,dc=flowable,dc=com"
      FLOWABLE_IDM_LDAP_PASSWORD: "admin_password"
      
      FLOWABLE_IDM_LDAP_USER_DN_PATTERN: "uid={0},ou=users,dc=flowable,dc=com"
      
      FLOWABLE_IDM_LDAP_ATTRIBUTE_USER_ID: uid
      FLOWABLE_IDM_LDAP_ATTRIBUTE_FULL_NAME: cn
      FLOWABLE_IDM_LDAP_ATTRIBUTE_EMAIL: mail
      FLOWABLE_IDM_LDAP_ATTRIBUTE_FIRST_NAME: givenName
      FLOWABLE_IDM_LDAP_ATTRIBUTE_LAST_NAME: sn



      FLOWABLE_COMMON_APP_IDM_ADMIN_GROUP: Admin
      FLOWABLE_IDM_CONFIG_MODELER_GROUPS: Admin
      FLOWABLE_IDM_CONFIG_TASK_GROUPS: Admin,Taskers
      FLOWABLE_IDM_CONFIG_ADMIN_GROUPS: Admin

      FLOWABLE_IDM_LDAP_GROUP_BASE_DN: "ou=groups,dc=flowable,dc=com"

      FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_ID: cn
      FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_NAME: cn
      FLOWABLE_IDM_LDAP_ATTRIBUTE_GROUP_MEMBER: member

      FLOWABLE_IDM_APP_KEYCLOAK_ROLE_CLAIM_NAME: roles
      SERVER_PORT: 8080

      # Query
      FLOWABLE_IDM_LDAP_USER_SEARCH_FILTER: "(uid={0})"
      FLOWABLE_IDM_LDAP_QUERY_ALL_USERS: "(objectClass=inetOrgPerson)"
      FLOWABLE_IDM_LDAP_GROUP_SEARCH_FILTER: "(member={0})"
      FLOWABLE_IDM_LDAP_QUERY_ALL_GROUPS: "(objectClass=groupOfNames)"

      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      LOGGING_LEVEL_ORG_FLOWABLE_IDM_ENGINE_IMPL_LDAP: DEBUG
    ports:
      - "6660:8080"
    networks:
      - shared-network
networks:
  shared-network:
    external: true
    name: flowable-keycloak-net
