# Server Config
server.port=8187

# Spring Config
spring.application.name=payment-srv
spring.profiles.active=dev
spring.config.import=optional:configserver:${VAULT_URL:http://localhost:8185}
spring.cloud.config.token=${VAULT_TOKEN}

# Database Config
spring.datasource.url=${application.database.base-url}/j2n_payment?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${application.database.username}
spring.datasource.password=${application.database.password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.cloud.compatibility-verifier.enabled=false

# PayOS Config
payos.client-id=your-client-id
payos.api-key=your-api-key
payos.checksum-key=your-checksum-key

## = RabbitMQ Configuration
spring.rabbitmq.host=${application.rabbitmq.host}
spring.rabbitmq.port=${application.rabbitmq.port}
spring.rabbitmq.username=${application.rabbitmq.username}
spring.rabbitmq.password=${application.rabbitmq.password}
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3

## = Redis Configuration
spring.data.redis.host=${application.redis.host}
spring.data.redis.port=${application.redis.port}
spring.data.redis.password=${application.redis.password}
spring.data.redis.database=0
spring.data.redis.timeout=${application.redis.timeout}

## = Swagger Configuration
spring.api-docs.enabled=true
spring.swagger-ui.enabled=true

## = Logging Configuration
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG