CREATE TABLE IF NOT EXISTS product_info (
    id BIGINT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    stock INT DEFAULT 0,
    thumbnail VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
