# Server Config
server.port=8189

# Spring Config
spring.application.name=room-srv
spring.profiles.active=dev
spring.config.import=optional:configserver:${VAULT_URL:http://localhost:8185}
spring.cloud.config.token=${VAULT_TOKEN}

# Database Config
spring.datasource.url=${application.database.base-url}/j2n_room?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${application.database.username}
spring.datasource.password=${application.database.password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.cloud.compatibility-verifier.enabled=false

## = RabbitMQ Configuration
spring.rabbitmq.host=${application.rabbitmq.host}
spring.rabbitmq.port=${application.rabbitmq.port}
spring.rabbitmq.username=${application.rabbitmq.username}
spring.rabbitmq.password=${application.rabbitmq.password}
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.dead-letter-message-ttl=${application.rabbitmq.dead-letter-message-ttl}

## = Redis Configuration
spring.data.redis.host=${application.redis.host}
spring.data.redis.port=${application.redis.port}
spring.data.redis.password=${application.redis.password}
spring.data.redis.database=0
spring.data.redis.timeout=${application.redis.timeout}

## = Swagger Configuration
spring.api-docs.enabled=true
spring.swagger-ui.enabled=true

## = Security Configuration
internal.token=${application.security.internal-token:j2n-internal-secret-token}

## = Logging Configuration
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
logging.level.com.example.j2n.room_srv.filter=DEBUG
