spring.application.name=report-srv
server.port=8184
spring.jackson.property-naming-strategy=SNAKE_CASE

spring.datasource.url=jdbc:mysql://localhost:3306/j2n_report?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Welcome1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.api-docs.enabled=true
spring.swagger-ui.enabled=true

internal.token=${INTERNAL_TOKEN:J2N-i9n1ofG7kL2mP9qRtVxZ4sB8nC1yHjDdUwAeIoPkLmQrStUvWxYzAbCReportSrv}

spring.rabbitmq.host=localhost
spring.rabbitmq.port=9192
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3

spring.data.redis.host=localhost
spring.data.redis.port=9194
spring.data.redis.password=yourpassword123
spring.data.redis.database=0
spring.data.redis.timeout=10000