-- Lấy ID của các permissions
SET @CAN_ASSIGN_ROLE_ID = (SELECT id FROM permissions WHERE name = 'CAN_ASSIGN_ROLE' LIMIT 1);
SET @CAN_CREATE_USER_ID = (SELECT id FROM permissions WHERE name = 'CAN_CREATE_USER' LIMIT 1);
SET @CAN_DELETE_USER_ID = (SELECT id FROM permissions WHERE name = 'CAN_DELETE_USER' LIMIT 1);
SET @CAN_VIEW_MANAGEMENT_PAGE_ID = (SELECT id FROM permissions WHERE name = 'CAN_VIEW_MANAGEMENT_PAGE' LIMIT 1);

-- Insert dependencies
INSERT IGNORE INTO permission_dependencies (permission_id, depends_on_id) VALUES
    (@CAN_ASSIGN_ROLE_ID, @CAN_VIEW_MANAGEMENT_PAGE_ID),
    (@CAN_CREATE_USER_ID, @CAN_VIEW_MANAGEMENT_PAGE_ID),
    (@CAN_DELETE_USER_ID, @CAN_VIEW_MANAGEMENT_PAGE_ID);
