query Op_getAllCategories {
  getAllCategories {
    code
    message
    data {
      id
      name
      slug
      type
    }
  }
}

query Op_getCategoryById($id: ID!) {
  getCategoryById(id: $id) {
    code
    message
    data {
      id
      name
      slug
      type
    }
  }
}

query Op_getCategoryBySlug($slug: String!) {
  getCategoryBySlug(slug: $slug) {
    code
    message
    data {
      id
      name
      slug
      type
    }
  }
}

query Op_getCategoryByName($name: String!) {
  getCategoryByName(name: $name) {
    code
    message
    data {
      id
      name
      slug
      type
    }
  }
}

query Op_getCategoriesByType($type: String!) {
  getCategoriesByType(type: $type) {
    code
    message
    data {
      id
      name
      slug
      type
    }
  }
}

mutation Op_createCategory($input: CategoryInput!) {
  createCategory(input: $input) {
    code
    message
    data {
      id
      name
      slug
    }
  }
}

mutation Op_updateCategory($id: ID!, $input: CategoryInput!) {
  updateCategory(id: $id, input: $input) {
    code
    message
    data {
      id
      name
      slug
    }
  }
}

mutation Op_deleteCategory($id: ID!) {
  deleteCategory(id: $id) {
    code
    message
    data
  }
}
