query Op_getSchedulesByTourId($tourId: ID!) {
  getSchedulesByTourId(tourId: $tourId) {
    code
    message
    data {
      id
      dayNumber
      title
      content
      createdAt
      updatedAt
    }
  }
}

mutation Op_addScheduleToTour($input: TourScheduleInput!) {
  addScheduleToTour(input: $input) {
    code
    message
    data {
      id
      dayNumber
      title
      content
      createdAt
      updatedAt
    }
  }
}

mutation Op_updateTourSchedule($id: ID!, $input: TourScheduleInput!) {
  updateTourSchedule(id: $id, input: $input) {
    code
    message
    data {
      id
      dayNumber
      title
      content
      createdAt
      updatedAt
    }
  }
}

mutation Op_deleteTourSchedule($id: ID!) {
  deleteTourSchedule(id: $id) {
    code
    message
    data
  }
}
