spring.application.name=travel-srv
spring.profiles.active=dev
server.port=8186
#spring.jackson.property-naming-strategy=SNAKE_CASE

spring.config.import=optional:configserver:${VAULT_URL:http://localhost:8185}
spring.cloud.config.token=${VAULT_TOKEN}

spring.cloud.compatibility-verifier.enabled=false

# MySQL Database Configuration
spring.datasource.url=${application.database.base-url}/j2n_travel?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${application.database.username}
spring.datasource.password=${application.database.password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Spring GraphQL Configuration
spring.graphql.path=/travel/graphql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/travel/graphiql
spring.graphql.schema.locations=classpath:graphql/

## = RabbitMQ Configuration
spring.rabbitmq.host=${application.rabbitmq.host}
spring.rabbitmq.port=${application.rabbitmq.port}
spring.rabbitmq.username=${application.rabbitmq.username}
spring.rabbitmq.password=${application.rabbitmq.password}
spring.rabbitmq.virtual-host=/
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
logging.level.org.springframework.security=DEBUG
