import type { Metadata } from "next";
import {
  Saira_Condensed,
  Noto_Sans_KR,
  Noto_Sans_JP,
  Merienda,
} from "next/font/google";
import { MantineProvider } from "@mantine/core";
import { I18nProvider } from "@/lib/i18n/provider";
import J2NHeader from "@repo/components/molecules/J2NHeader";
import "@repo/ui/src/styles/globals.css";
import "@mantine/core/styles.css";

const saira = Saira_Condensed({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-primary",
});

const notoKR = Noto_Sans_KR({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "latin-ext", "vietnamese", "cyrillic"],
  variable: "--font-primary-kr",
});

const notoJP = Noto_Sans_JP({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "latin-ext", "vietnamese", "cyrillic"],
  variable: "--font-primary-jp",
});

const merienda = Merienda({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin", "latin-ext"],
  variable: "--font-secondary",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${saira.variable} ${notoKR.variable} ${notoJP.variable} ${merienda.variable} antialiased`}
      >
        <MantineProvider>
          <I18nProvider>
            <J2NHeader logoSrc="https://png.pngtree.com/element_pic/00/16/09/2057e0eecf792fb.jpg" />
            <main>{children}</main>
          </I18nProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
