INSERT IGNORE INTO configurations (config_key, config_value, description)
VALUES
    ('portfolio.name', 'Jadon Nguyen', 'Tên portfolio'),
    ('portfolio.pre-introduction', 'Pre Introduction', '“I''m a Fullstack developer with about 6 years of experience, specializing in JavaScript, TypeScript, ReactJS and Java... “'),
    ('portfolio.main-introduction', 'Main Introduction', '"Hi, I''m a front-end developer with about 6 years of experience, specializing in JavaScript, TypeScript, and ReactJS. My journey in
        the tech industry has allowed me to work on several impactful company projects, where I''ve not only honed my front-end
        skills but also gained valuable insights into backend development with Java. While front-end development is my primary
        focus, I bring a well-rounded approach to my work, ensuring that my projects are robust and integrated seamlessly with
        backend systems."'),
    ('portfolio.skills', '{"core":[{"name":"ReactJS","experience":"6"},{"name":"Javasciprt","experience":"6"},{"name":"Typescript","experience":"6"},{"name":"Java Spring Boot","experience":"4"},{"name":"NextJS","experience":"4"}],"others":[{"name":"HTML","experience":"6"},{"name":"CSS","experience":"6"},{"name":"Tailwind","experience":"3"},{"name":"Sass/Less","experience":"6"},{"name":"Ant Design","experience":"6"},{"name":"Fluent UI","experience":"2"},{"name":"Docker","experience":"2"},{"name":"Kubenetes","experience":"2"},{"name":"NodeJS","experience":"1"},{"name":"NestJS","experience":"Personal Project"},{"name":"RabbitMQ","experience":"Personal Project"},{"name":"Redux","experience":"6"},{"name":"Zustand","experience":"1"},{"name":"Firebase","experience":"1"},{"name":"React Native","experience":"1"},{"name":"GraphQL","experience":"Personal Project"},{"name":"PostgreSQL","experience":"Personal Project"}]}', 'Experience Skills/Tools'),
    ('portfolio.time-line', '[{"title":"University Of Economics - Technology For Industries Systems","subtitle":"Major in Information Technology","description":"","period":"2014 - 2019"},{"title":"Travel Connect","subtitle":"Frontend Developer","description":"Travel Connect is a startup providing travel package solutions for both B2B and B2C clients, offering flexible, transparent, and cost-optimized tour options.","period":"12/2019 - 05/2020"},{"title":"Add-on Development","subtitle":"Frontend Developer","description":"Add-On delivers resource scheduling solutions that streamline meeting management. Users can find available rooms, reduce cancellations, and manage services directly in Microsoft Outlook whether on-premise, in a private cloud, or as a SaaS solution.","period":"06/2020 - 12/2022"},{"title":"Cafe Review","subtitle":"Frontend Developer","description":"Cafe Review is a short-term outsourced project that provides an online news platform capable of crawling articles automatically from selected sources while also supporting manual content creation.","period":"11/2020 - 06/2021"},{"title":"Add-on Development","subtitle":"Leader Frontend Team","description":"Add-On delivers resource scheduling solutions that streamline meeting management. Users can find available rooms, reduce cancellations, and manage services directly in Microsoft Outlook whether on-premise, in a private cloud, or as a SaaS solution.","period":"01/2022 - 08/2022"},{"title":"Ascend Technology","subtitle":"Fullstack Developer","description":"Ascend Technology develops the core e-payment platform powering TrueMoney services, including Wallet, WeCard, CashCard, kiosks, payment gateways, and remittance solutions.","period":"08/2022 - Present"}]', 'Career Timeline'),
    ('store-portal.base-url', 'http://localhost:3104', 'URL cơ bản của store-portal'),
    ('room-portal.base-url', 'http://localhost:3103', 'URL cơ bản của room-portal'),
    ('management-portal.base-url', 'http://localhost:3102', 'URL cơ bản của management-portal'),
    ('system-portal.base-url', 'http://localhost:3101', 'URL cơ bản của system-portal'),
    ('about-portal.base-url', 'http://localhost:3100', 'URL cơ bản của about-portal');
