syntax = "proto3";

package com.example.j2n.lib.proto;

import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";

option java_multiple_files = true;
option java_package = "com.example.j2n.lib.proto";
option java_outer_classname = "ReportProto";

service ReportService {
  // Lấy dữ liệu Dashboard
  rpc GetDashboardReport(GetDashboardRequest) returns (BaseProtoResponse);

  // Nội bộ: Gateway gọi để lấy danh sách API
  rpc GetApiCatalog(google.protobuf.Empty) returns (ApiCatalogResponse);
}

message ApiCatalogResponse {
  map<string, string> mappings = 1;
}

message GetDashboardRequest {
  // Thông tin user được lấy từ gRPC Metadata (Header)
}

message BaseProtoResponse {
  int32 code = 1;       // HTTP/Business Status Code
  string message = 2;    // Thông báo kết quả
  google.protobuf.Struct data = 3; // JSON Object động
}
