CREATE TABLE IF NOT EXISTS product_info (
    id     BIGINT PRIMARY KEY,
    title  VARCHAR(255)   NOT NULL,
    price  DECIMAL(19, 2) NOT NULL,
    thumbnail VARCHAR(500),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
